spring.application.name=ventas

server.port=8080

# Conexion al MySQL local de Laragon
spring.datasource.url=jdbc:mysql://ecommerce-1.crw6gxoa4ucv.us-east-1.rds.amazonaws.com/ventas_publicador
spring.datasource.username=admin
spring.datasource.password=Qnx640140!

# Persistencia con JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Mostrar las consultas SQL durante el aprendizaje
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
